# postgres database connection
database:
  login: 'postgres' # логин
  password: 'qwerty' # пароль
  url: 'localhost' # url подключения
  name: 'minecraft_server_db' # название бд

# level limit
levellimit:
  enable: true # включить/выключить ограничение опыта
  max_level: 30 # максимальный уровень игрока

betterhorses:
  enable: true # включить/выключить улучшенных лошадей